version: '2'

services:
  # ----------------------------------------------------------------- backend

  # ----------------------------------------------------------------- frontend

  # ----------------------------------------------------------------- db

  argos-db:
    container_name: argos-db
    image: mongo:4.4.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - db:/data/db
    ports:
      - 27017:27017

  # ----------------------------------------------------------------- db utility
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: argos-db
      ME_CONFIG_OPTIONS_EDITORTHEME: material
    depends_on:
      - argos-db

volumes:
  db: