version: '2'

services:
  # ----------------------------------------------------------------- backend
  argos:
    image: 'docker-spring-boot-mongodb:latest'
    build:
      context: .
    container_name: argos
    depends_on:
      - postgres
    environment:
      - SPRING.DATA.MONGODB.USERNAME=admin
      - spring.data.mongodb.password=admin
      - spring.data.mongodb.authentication-database=admin
      - spring.data.mongodb.database=admin

  # ----------------------------------------------------------------- frontend

  # ----------------------------------------------------------------- db

  argos-db:
    container_name: argos-db
    image: mongo:4.4.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - db:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: argos-db
      ME_CONFIG_OPTIONS_EDITORTHEME: material
    depends_on:
      - argos-db

volumes:
  db: